import { GameData } from '../models/gameData.model';

export const gotmWinners: GameData[] = [
  {
    img: 'https://cdn.mobygames.com/screenshots/10940072-sin-and-punishment-wii-whats-going-on-achi-girl-in-blue-and-hell.jpg',
    title: 'Sin & Punishment',
    year: 2000,
    system: 'N64',
    developer: 'Treasure',
    genre: 'Rail Shooter',
    timeToBeat: 2,
    description:
      'This is an incredibly kickass on-rails shooter from Treasure that is every bit as good as any Star Fox or Panzer Dragoon game.  Play as either Saki or Airan while fighting off mutants in Japan in the distant dystopian future of 2007.  While initially only released in Japan, all the dialogue is in English anyway so this is an easy one to play even without a translation patch.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16580786-harmful-park-playstation-this-type-of-explosion-will-always-occu.png',
    title: 'Harmful Park',
    year: 1997,
    system: 'PS1',
    developer: 'Sky Think System',
    genre: "Shoot 'em Up",
    timeToBeat: 1,
    description:
      'Wild, colorful, goofy, charming shmup action in a dangerous theme park! A game in the same vein as the Parodius series.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10526434-astal-sega-saturn-stage-4-river-of-dreamsin-this-stage-you-even-.jpg',
    title: 'Astal',
    year: 1995,
    system: 'Saturn',
    developer: 'Sega',
    genre: 'Platformer',
    timeToBeat: 1,
    description:
      'An early release on the Sega Saturn, it was largely ignored for being a 2D platformer on a system expected to produce 3D titles, but its graphics have aged better than 3D titles of the time. Its box art on the other hand...',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16480150-vagrant-story-playstation-oh-yeah-and-you-fight-like-a-cow.png',
    title: 'Vagrant Story',
    year: 2000,
    system: 'PS1',
    developer: 'Squaresoft',
    genre: 'ARPG',
    timeToBeat: 24,
    description:
      'Play as Ashley Riot, a Riskbreaker exploring the link between a cult leader and a senior Parliament member, Duke Bardorba, in the Kingdom of Valendia. Using a pauseable real-time combat mechanic (similar to Parasite Eve) and deep weapon crafting system, fight your way through undead, phantoms, beasts, and other unsettling enemies as you explore the catacombs of the ruined city Leá Monde.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10341521-parasite-eve-ii-playstation-aya-is-talking-to-a-policeman.jpg',
    title: 'Parasite Eve II',
    year: 1999,
    system: 'PS1',
    developer: 'Squaresoft',
    genre: 'ARPG/Survival Horror',
    timeToBeat: 12,
    description:
      'Aya is back and so is that pesky mitochondria. Instead of the turn based rpg style of the first one, the sequel is more action based/survival horror. It still retains some of that rpg goodness though.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1618871-castlevania-rondo-of-blood-turbografx-cd-giant-bat.png',
    title: 'Castlevania: Rondo of Blood',
    year: 1993,
    system: 'TG-CD/PCE-CD, PSP',
    developer: 'Konami',
    genre: 'Action-Platformer',
    timeToBeat: 4,
    description:
      'Guide Richter Belmont through Dracula’s castle as he tries to save his beloved Annette and others kidnapped by Dracula’s servants.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/9167297-pokemon-conquest-nintendo-ds-dramatic-pokemon-expressions.jpg',
    title: 'Pokemon Conquest',
    year: 2012,
    system: 'DS',
    developer: 'Tecmo Koei',
    genre: 'TRPG',
    timeToBeat: 14,
    description:
      "A crossover between Pokemon and the acclaimed Nobunaga's Ambition, Pokemon Conquest takes elements from both series to create a fun and unique tactical experience. Perfect for both newcomers and veterans of the genre, Pokemon Conquest lets everyone experience the fun of tactics.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10361302-r4-ridge-racer-type-4-playstation-while-in-first-person-mode-you.jpg',
    title: 'R4: Ridge Racer Type 4',
    year: 1999,
    system: 'PS1',
    developer: 'Namco',
    genre: 'Racing',
    timeToBeat: 2,
    description:
      'Choose one of four teams to drive for and compete in the Real Racing Roots ‘99 Grand Prix in this classic racing game. Regarded as one of the best racers on the system and still beloved as the best game in the ridge racer franchise.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1023760-teenage-mutant-ninja-turtles-turtles-in-time-snes-the-foot-soldi.png',
    title: 'Teenage Mutant Ninja Turtles: Turtles in Time',
    year: 1992,
    system: 'SNES, Arcade',
    developer: 'Konami',
    genre: "Beat 'em Up",
    timeToBeat: 1,
    description:
      "Play as one of the four Ninja Turtles in this rad Beat em' Up through the Ages!",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15838084-dragon-ball-advanced-adventure-game-boy-advance-victory.png',
    title: 'Dragon Ball: Advanced Adventure',
    year: 2004,
    system: 'GBA',
    developer: 'Dimps',
    genre: "Beat 'em Up",
    timeToBeat: 4,
    description:
      "In this 2D side-scrolling beat 'em up, special items can be collected throughout each stage, including those that increase the player's health and/or ki, and Dragon Balls. Clearing the story mode unlocks the ability to play as Krillin. The story mode is divided in various stage types; including standard platforming levels, flying stages, and one-on-one battles.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/12456986-choro-q-wonderful-playstation-shopping-street.png',
    title: 'ChoroQ Wonderful!',
    year: 1999,
    system: 'PS1',
    developer: 'E-Game',
    genre: 'Racing RPG',
    timeToBeat: Number.MAX_SAFE_INTEGER,
    description:
      'The latest translated Choro Q game is said to be the stepping stone between the old, classic Choro Q games and the new, more heavily CarPG focused games. Race, upgrade your car and do quests in the over world; Talk about Wonderful!',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/393381-world-of-illusion-starring-mickey-mouse-and-donald-duck-genesis-.png',
    title: 'World of Illusion Starring Mickey Mouse and Donald Duck',
    year: 1992,
    system: 'Genesis/MD',
    developer: 'Sega',
    genre: 'Platformer',
    timeToBeat: 2,
    description:
      "Play as Mickey or Donald as they use their magic capes to go through the world of illusion in one of the best platformers on the genesis. This game has no right to be as good as it is. Plus it's a nice short 2 hour jaunt. May contain violence.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16508941-egg-elemental-gimmick-gear-dreamcast-a-boss-battle-in-this-case-.png',
    title: 'E.G.G.: Elemental Gimmick Gear',
    year: 1999,
    system: 'DC',
    developer: 'Hudsonsoft',
    genre: 'Action-Adventure',
    timeToBeat: 14,
    description:
      'You are a man found inside a buried egg shaped robot in a deep slumber. Traverse this beautiful hand drawn adventure with 3D graphic boss battles.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16040632-metroid-zero-mission-game-boy-advance-back-on-the-surface.png',
    title: 'Metroid: Zero Mission',
    year: 2004,
    system: 'GBA',
    developer: 'Nintendo R&D1',
    genre: 'Metroidvania',
    timeToBeat: 5,
    description:
      'A remake of the original Metroid where the player controls bounty hunter Samus Aran, who travels to planet Zebes after learning that the Space Pirates are experimenting with Metroids, hostile parasitic creatures.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15734982-mega-man-2-nes-heat-mans-stage.png',
    title: 'Mega Man 2',
    year: 1988,
    system: 'NES',
    developer: 'Capcom',
    genre: 'Action-Platformer',
    timeToBeat: 3,
    description:
      "Mega Man 2 is an action game developed and published by Capcom for the Nintendo Entertainment System. It was released in Japan in 1988 and in North America and PAL regions the following years. Mega Man 2 continues Mega Man's battle against the evil Dr. Wily and his rogue robots. It introduced graphical and gameplay changes, many of which became series staples.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/11493568-perfect-dark-xbox-360-harsh-didnt-even-let-him-get-out-of-the-ch.jpg',
    title: 'Perfect Dark',
    year: 2000,
    system: 'N64',
    developer: 'Rare',
    genre: 'FPS',
    timeToBeat: 9,
    description:
      'Perfect Dark is a dystopian sci-fi FPS where you play as newly minted secret agent Joanna "Perfect" Dark, uncovering a sinister, very far reaching conspiracy.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10531148-mystical-ninja-starring-goemon-nintendo-64-two-sinister-figures-.jpg',
    title: 'Mystical Ninja Starring Goemon',
    year: 1997,
    system: 'N64',
    developer: 'Konami',
    genre: 'Action-Adventure',
    timeToBeat: 10,
    description:
      'Mystical Ninja Starring Goemon is a platform action-adventure video game released by Konami for the Nintendo 64 on August 7, 1997 in Japan, April 16, 1998 in North America, and 18 April 1998 in Europe as the fifth entry in the Ganbare Goemon series. The second Goemon game released in North America and Europe, it follows The Legend of the Mystical Ninja and features hybrid elements of platform games and action-adventure games.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/3394573-beyond-oasis-genesis-he-is-met-with-some-unexpected-opposition.png',
    title: 'Beyond Oasis',
    year: 1994,
    system: 'Genesis/MD',
    developer: 'Ancient',
    genre: 'ARPG',
    timeToBeat: 6,
    description:
      'Control spirits with the power of the armlet in this ARPG on the genesis. Solid combat mechanics and fun puzzles make this one my favorite Zelda-like of the 16-bit era. And Bill likes it too.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15764364-klonoa-empire-of-dreams-game-boy-advance-after-defeating-that-gi.png',
    title: 'Klonoa: Empire of Dreams',
    year: 2001,
    system: 'GBA',
    developer: 'Now Production',
    genre: 'Platformer',
    timeToBeat: 6,
    description: '',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/11177293-banjo-kazooie-xbox-360-hiding-from-the-snowmen-under-the-water.jpg',
    title: 'Banjo-Kazooie',
    year: 1998,
    system: 'N64',
    developer: 'Rareware',
    genre: 'Platformer',
    timeToBeat: 11,
    description:
      "There's so much water in this game. Even FROZEN water. Go on this Bear and Bird water platforming adventure.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1077006-enduro-atari-2600-title-screen-game-demo.png',
    title: 'Enduro',
    year: 1983,
    system: 'Atari 2600, GBA, Android',
    developer: 'Activision',
    genre: 'Racing',
    timeToBeat: Number.MAX_SAFE_INTEGER,
    description:
      "A true classic with surprising performance for it's hardware, Enduro is a racing video game that features inclement weather, and a transition from day to night where you can only see others' taillights. Pass a specific number of cars each day to keep going, don't crash,  and make it through day 5 to win Activision's prize!",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16135044-wario-land-3-game-boy-color-inside-the-woods.png',
    title: 'Wario Land 3',
    year: 2000,
    system: 'GBC',
    developer: 'Nintendo R&D1',
    genre: 'Action',
    timeToBeat: 6,
    description:
      "Wario must take advantage of his enemies' attacks to physically change and access new areas. The game features a day/night cycle, and stages change depending on the time of day; certain enemies may be replaced or different paths may open up.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15891342-survival-kids-game-boy-color-take-this.png',
    title: 'Survival Kids',
    year: 1999,
    system: 'GBC',
    developer: 'Konami',
    genre: 'Survival',
    timeToBeat: 5,
    description:
      'You crash on a deserted island. Survive on the island with scavenging, crafting, fishing, and more until you find a way back to civilization!',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1292262-breath-of-fire-snes-this-gargoyle-is-just-a-saving-point-you-res.png',
    title: 'Breath of Fire',
    year: 1993,
    system: 'SNES',
    developer: 'Capcom',
    genre: 'RPG',
    timeToBeat: 28,
    description:
      "One of Capcom's greatest role-playing game franchises, Breath of Fire follows the journey of a boy named Ryu, one of the last surviving members of an ancient race with the ability to transform into mighty dragons, as he searches the world for his sister.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10288494-luigis-mansion-gamecube-ghost-training.jpg',
    title: "Luigi's Mansion",
    year: 2001,
    system: 'Gamecube, 3DS',
    developer: 'Nintendo',
    genre: 'Action-Adventure',
    timeToBeat: 7,
    description:
      'Mario is missing again in a haunted mansion, time for Luigi to play Ghost Buster while looking for his bro.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/631840-echo-night-playstation-talking-with-ghosts.jpg',
    title: 'Echo Night',
    year: 1998,
    system: 'PS1',
    developer: 'FromSoftware',
    genre: 'Adventure',
    timeToBeat: 5,
    description: '',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16859603-avenging-spirit-arcade-lets-go.png',
    title: 'Avenging Spirit',
    year: 1992,
    system: 'GB',
    developer: 'C.P. Brain',
    genre: 'Platformer',
    timeToBeat: 1,
    description: '',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1774703-the-legend-of-zelda-oracle-of-ages-game-boy-color-a-strange-boul.jpg',
    title: 'The Legend of Zelda: Oracle of Ages',
    year: 2001,
    system: 'GBC',
    developer: 'Flagship',
    genre: 'Action Adventure',
    timeToBeat: 17,
    description:
      'A top down action-adventure game released in two separate versions: this version (Ages) being the more puzzle focused of the two entries. Name a more iconic sword and shield combination in gaming. I’ll wait.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10896733-castlevania-symphony-of-the-night-playstation-in-classic-castlev.jpg',
    title: 'Castlevania: Symphony of the Night',
    year: 1997,
    system: 'PS1, Saturn, PSP, Android',
    developer: 'Konami',
    genre: 'Metroidvania',
    timeToBeat: 9,
    description:
      "The heir to the Belmont lineage is MIA, and evil is stirring once again. Play the role of Alucard, Dracula's own son, in this​ legendary genre-defining Metroidvania.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15668504-ys-book-i-ii-turbografx-cd-adol-leaving-ship.png',
    title: 'Ys Book 1 & 2',
    year: 1989,
    system: 'TG-CD/PCE-CD',
    developer: 'Nihon Falcom',
    genre: 'ARPG',
    timeToBeat: 15,
    description:
      'The start of one of the best ARPG series. Has one of the best soundtracks I’ve heard, a great story, fast-paced combat that is very satisfying, challenging boss fights, and more. The game has been acclaimed by fans and critics alike since it’s release and still is regarded as one of the best games of all time by Electronic Gaming Monthly, IGN, Gamespot, and others.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16439321-999-nine-hours-nine-persons-nine-doors-nintendo-ds-objects-that-.png',
    title: '999 (Nine Hours, Nine Persons, Nine Doors)',
    year: 2009,
    system: 'Nintendo DS',
    developer: 'Chunsoft',
    genre: 'Visual Novel',
    timeToBeat: 9.5,
    description:
      'Do you like murder mysteries? Do you like puzzle games? Do you like good quality narrative told in a compelling manner? Then check out 999 a fantastic point and click puzzle mystery with a fantastic plot that keeps you guessing.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/11331689-klonoa-door-to-phantomile-playstation-shield-holding-enemies-can.jpg',
    title: 'Klonoa: Door to Phantomile',
    year: 1997,
    system: 'PS1',
    developer: 'Namco',
    genre: 'Platformer',
    timeToBeat: 4,
    description:
      "Klonoa: Door to Phantomile is a 2.5D platformer game and the first entry in the character's unfortunately short-lived game series. It has charm, dreams and platforming. Can't think of anything else a Playstation game would need.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1308543-ihatovo-monogatari-snes-playing-a-school-teacher.png',
    title: 'Ihatovo Monogatari',
    year: 1993,
    system: 'SNES',
    developer: 'Hect',
    genre: 'Adventure',
    timeToBeat: 4,
    description:
      "An extremely chill game where you collect the works of children's lit poet Kenji Miyazawa in a city populated by talking animals.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16134456-tomato-adventure-game-boy-advance-once-upon-a-time.png',
    title: 'Tomato Adventure',
    year: 2002,
    system: 'GBA',
    developer: 'AlphaDream',
    genre: 'RPG',
    timeToBeat: 11,
    description:
      "Don't want to play Superstar Saga again but something similar. With a great mini game type combat system. Give Tomato Adventure a try or don't.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10542736-medievil-playstation-crossing-the-water-in-dans-crypt.jpg',
    title: 'MediEvil',
    year: 1998,
    system: 'PS1, PS4',
    developer: 'SCE Studio Cambridge',
    genre: 'Action',
    timeToBeat: 6,
    description: '',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/2294572-terranigma-snes-angry-looking-metallic-guardians-hit-me-with-the.png',
    title: 'Terranigma',
    year: 1995,
    system: 'SNES',
    developer: 'Quintet',
    genre: 'ARPG',
    timeToBeat: 16,
    description:
      "The game tells the story of the Earth's resurrection by the hands of a boy named Ark, and its progress from the evolution of life to the present day. The game is played from a top-down perspective. Different attacks can be performed based on whether Ark is jumping, running, walking, or standing still.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/5424908-populous-ii-trials-of-the-olympian-gods-dos-another-kind-of-deat.png',
    title: 'Pokemon TCG2: The Invasion of Team GR!',
    year: 2001,
    system: 'GBC',
    developer: 'Nintendo',
    genre: 'Card Game',
    timeToBeat: Number.MAX_SAFE_INTEGER,
    description:
      'Pokémon Card GB2: Here Comes Team GR!, abbreviated Pokémon Card GB2, is the Japan-only sequel to Pokémon Trading Card Game. The game story revolves around a new villainous team, Team Great Rocket, and contains nearly all of the cards from Base Set, Jungle, Fossil, and Team Rocket.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/4478851-ganpuru-gunmans-proof-snes-dont-shoot-me-im-just-a-pianist.png',
    title: "Gunple: Gunman's Proof",
    year: 1997,
    system: 'SFC',
    developer: 'ASCII Media Works',
    genre: 'Action Adventure',
    timeToBeat: 4,
    description: '',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15785509-kaeru-no-tame-ni-kane-wa-naru-game-boy-after-being-beaten-up-you.png',
    title: 'Kaeru no Tame ni Kane wa Naru',
    year: 1992,
    system: 'GB',
    developer: 'Nintendo R&D1, Intelligent Systems',
    genre: 'ARPG',
    timeToBeat: 6,
    description:
      "Often compared to Link's Awakening, Its got both a top down bird's eye view as well as 2D platforming sections with a interesting battle system.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16232628-warioware-inc-mega-microgame-game-boy-advance-drop.png',
    title: 'Wario Ware, Inc.: Mega Microgame$!',
    year: 2003,
    system: 'GBA',
    developer: 'Nintendo',
    genre: 'Mini-Game Collection',
    timeToBeat: 2,
    description: 'Join the King of minigames',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1201237-super-mario-land-2-6-golden-coins-game-boy-map-of-the-land.png',
    title: 'Super Mario Land 2',
    year: 1992,
    system: 'GB',
    developer: 'Nintendo',
    genre: 'Platformer',
    timeToBeat: 3,
    description: '',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/5612440-phoenix-wright-ace-attorney-iphone-that-brat-is-pretty-though.png',
    title: 'Phoenix Wright: Ace Attorney',
    year: 2005,
    system: 'DS, PS4, Switch',
    developer: 'Capcom',
    genre: 'Visual Novel',
    timeToBeat: 18,
    description:
      'Step into the shoes of Phoenix Wright, somewhat competent defense attorney, in this wacky courtroom simulator. Find evidence, interrogate witness, expose their lies and find the truth!',
  },
  {
    img: 'https://screenscraper.fr/image.php?gameid=5647&media=ss&hd=0&region=jp&num=&version=&maxwidth=640&maxheight=480',
    title: 'Custom Robo',
    year: 1999,
    system: 'Nintendo 64',
    developer: 'Noise',
    genre: 'Action RPG',
    timeToBeat: Number.MAX_SAFE_INTEGER,
    description:
      'Build your tiny robot and do battle with other Custom Robos in the Holosseum! A unique action game with RPG elements that spawned a franchise. Thanks to a fan translation, now English-speakers can enjoy the original Custom Robo!',
  },
  {
    img: 'https://screenscraper.fr/image.php?gameid=20580&media=ss&hd=0&region=jp&num=&version=&maxwidth=640&maxheight=480',
    title: 'Choro Q 3',
    year: 1998,
    system: 'PS1',
    developer: 'Tamsoft/Takara',
    genre: 'Racing',
    timeToBeat: 4,
    description:
      "Get your CaRPG on! In this cute racing game based on the Japanese toy car company of the same name, (you may remember them as Penny or Gadget Racers), you'll aim for the Hyper GP as you upgrade your car with the money you earn in races. Besides racing, there's a huge city to explore to find new shops, 100 different events, mini games, and more!",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16417580-outrun-arcade-lets-go.png',
    title: 'OutRun',
    year: 1986,
    system: 'Arcade',
    developer: 'Sega',
    genre: 'Racing',
    timeToBeat: 1,
    description:
      'Get Ready…for the classic racer game that pushed graphical limitations back in the 80s. With its aesthetics; the colorful graphics, great music and charm, its no wonder why this game got ported to so many systems/consoles to this day.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15775137-drill-dozer-game-boy-advance-you-can-scope-out-your-surroundings.png',
    title: 'Drill Dozer',
    year: 2005,
    system: 'Game Boy Advance',
    developer: 'Game Freak',
    genre: 'Action/Platform',
    timeToBeat: 5.5,
    description:
      'Drill Dozer is an action platformer developed by acclaimed publisher Gamefreak of Pokémon fame. It’s a gorgeous, colorful story, following a gang of mech-wielding scrapyard workers/bandits with a heart of gold as you tackle the nefarious rival gang of the Skullkers. You battle your way to reclaim a family jewel and uncover the mystery behind its power.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15879896-rayman-2-the-great-escape-windows-lava.png',
    title: 'Rayman 2: The Great Escape',
    year: 1999,
    system: 'PS1/N64',
    developer: 'Ubisoft',
    genre: 'Platformer',
    timeToBeat: 8,
    description:
      'An absolute classic and a key part of 3D platforming history which still holds up today. One of the most iconic mascots in gaming, in this adventure Rayman is taking on robot pirates. Robot. Pirates. Could that be any cooler?',
  },
  {
    img: 'https://screenscraper.fr/image.php?gameid=12726&media=ss&region=wor&num=&version=&maxwidth=640&maxheight=480',
    title: 'Snatcher',
    year: 1988,
    system: 'Sega CD/PS1',
    developer: 'Konami',
    genre: 'Graphic Adventure',
    timeToBeat: 8,
    description:
      'Snatcher is a cyberpunk graphic adventure game developed and published by Konami. It was written and designed by Hideo Kojima and first released in 1988 for the PC-8801 and MSX2 in Japan. Snatcher is set in a future East Asian metropolis where humanoid robots dubbed "Snatchers" have been discovered killing humans and replacing them in society. The game follows Gillian Seed, an amnesiac who joins an anti-Snatcher agency in search of his past. Gameplay takes place primarily through a menu-based interface through which the player can choose to examine items, search rooms, speak to characters, explore a semi-open world, and perform other actions.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16468876-the-legend-of-zelda-the-minish-cap-game-boy-advance-first-weapon.png',
    title: 'The Legend of Zelda: The Minish Cap',
    year: 2005,
    system: 'GBA',
    developer: 'Capcom/Nintendo',
    genre: 'Action Adventure',
    timeToBeat: 16,
    description:
      'The Legend of Zelda: The Minish Cap is an action-adventure video game and the twelfth entry in The Legend of Zelda series. Developed by Capcom and Flagship, with Nintendo overseeing the development process, Minish Cap was released for the Game Boy Advance in Japan and Europe in 2004 and in North America and Australia the following year. In June 2014, it was made available on the Wii U Virtual Console.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10272063-kirby-super-star-snes-watch-out-enemies-and-walls-this-kirby-sho.jpg',
    title: 'Kirby Super Star',
    year: 1996,
    system: 'SNES/DS',
    developer: 'HAL Laboratory',
    genre: 'Platformer',
    timeToBeat: 4,
    description:
      'This pinnacle of pink puff platforming premiered partners! Kirby Super Star contains a half-dozen mini Kirby adventures, and lets you bring a co-cop couch partner along as a “Helper” character. This surprisingly deep platformer has enough secrets to keep you constantly coming back for more, and features over twenty unique copy abilities to learn and master! The DS remaster adds a few more game modes and updated pixel art graphics.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1013065-gunstar-heroes-game-gear-in-this-stage-youll-be-flying-this-heli.png',
    title: 'Gunstar Heroes',
    year: 1993,
    system: 'Genesis/MD',
    developer: 'Treasure',
    genre: 'Action Platformer',
    timeToBeat: 2,
    description:
      'Gunstar Heroes is a run and gun game played from a side-scrolling perspective and can be played in single-player, or cooperatively with a partner.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15869910-golden-sun-game-boy-advance-portal.png',
    title: 'Golden Sun',
    year: 2001,
    system: 'GBA',
    developer: 'Camelot',
    genre: 'RPG',
    timeToBeat: 22,
    description:
      "Golden Sun is a contemporary presentation of the traditional role-playing video game formula, in which the player controls a cast of four characters as they journey through a fantasy-themed world, interact with other characters, battle monsters, acquire increasingly powerful abilities and equipment, and take part in an ongoing narrative.  Although many of the player's actions are compulsory, Golden Sun often allows the player to visit previous locations and complete certain objectives out of order.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15848769-brave-fencer-musashi-playstation-action-figures-shop.png',
    title: 'Brave Fencer Musashi',
    year: 1998,
    system: 'PS1',
    developer: 'Square',
    genre: 'ARPG',
    timeToBeat: 15,
    description:
      "Believe it or don't, there was a time when Square was more ambitious about experimenting with ideas and genres outside of Final Fantasy! This is one of those!",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/3774925-crusader-of-centy-genesis-inside-the-mountain.png',
    title: 'Crusader of Centy/Soleil',
    year: 1994,
    system: 'Genesis/MD',
    developer: 'Nextech',
    genre: 'Action Adventure',
    timeToBeat: 8,
    description:
      'You play as Corona, a 14 year old who must train to fight. You can speak with and recruit plants/animals to help you with their special abilities.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/11513017-paper-mario-nintendo-64-fighting-a-pair-of-stone-chomps.jpg',
    title: 'Paper Mario',
    year: 2000,
    system: 'N64',
    developer: 'Intelligent Systems',
    genre: 'RPG',
    timeToBeat: 23,
    description:
      "When Princess Peach is kidnapped, Mario plots to rescue the seven Star Spirits and rid the Mushroom Kingdom of Bowser's cruel cohorts. As he travels from the tropical jungles of Lavalava Island to the frosty heights of Shiver Mountain, he’ll meet up with seven all-new companions…and he’ll need help from each one or there’ll be no happily ever after.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1147599-star-ocean-snes-ratix-in-his-home-town.png',
    title: 'Star Ocean',
    year: 1996,
    system: 'SNES/PSP',
    developer: 'tri-ace',
    genre: 'RPG',
    timeToBeat: 21,
    description:
      'The story involves three friends who, while searching for the cure to a new disease, come into contact with a space-faring federation that is locked in a war with another galactic power. Using advanced technologies and time travel, the group attempts to uncover the cause of the war and to find a cure for their planet',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/12203436-sonic-the-hedgehog-3-knuckles-windows-play-as-knuckles.jpg',
    title: 'Sonic the Hedgehog 3 & Knuckles',
    year: 0,
    system: 'Sega Genesis',
    developer: 'Sega',
    genre: 'Platformer',
    timeToBeat: Number.MAX_SAFE_INTEGER,
    description: '',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/12272450-metal-slug-3-windows-lots-of-mutants-but-there-is-some-unexpecte.jpg',
    title: 'Metal Slug 3',
    year: 2000,
    system: 'Neo Geo',
    developer: 'SNK',
    genre: "Run 'n Gun",
    timeToBeat: 2,
    description:
      'Mission Start! You want vehicles? How about Super Vehicles? Take control of tanks, helicopters, armored camels, and more in this gorgeous pixel art run-and-gun classic!',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16646642-star-fox-64-wii-a-warp-portal.png',
    title: 'Star Fox 64',
    year: 1997,
    system: 'N64',
    developer: 'Nintendo',
    genre: 'Rail Shooter',
    timeToBeat: 2,
    description:
      'Star Fox 64 invites players to take on the role of legendary Fox McCloud as they lead a fearless squadron of fighters in fierce aerial combat to battle the evil forces of Andross and save the galaxy from destruction.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/490787-front-mission-snes-preparing-a-ranged-technique.png',
    title: 'Front Mission',
    year: 1995,
    system: 'SNES',
    developer: 'Squaresoft',
    genre: 'SRPG',
    timeToBeat: 22,
    description:
      'Front Mission, a tactical role-playing game, is part of a serialized storyline that follows the stories of various characters and their struggles involving mecha known as Wanzers.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/117875-doom-rpg-j2me-lots-of-blood-and-level-up.png',
    title: 'Doom RPG',
    year: 2005,
    system: 'Mobile',
    developer: 'Id Software',
    genre: 'RPG',
    timeToBeat: 5,
    description:
      'An exciting new direction for Doom, less frantic but extremely well realized (as expected of John Carmack, who wrote the engine in a week during his honeymoon). Very interesting gameplay and a blend of Doom 1 graphics with Doom 3 plot plots for the scenario.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/690583-silent-hill-playstation-bloody-scenes-will-never-lack-especially.jpg',
    title: 'Silent Hill',
    year: 1999,
    system: 'PS1',
    developer: 'Konami',
    genre: 'Survival Horror',
    timeToBeat: 7,
    description:
      'Trapped in the eponymous town of Silent Hill, Harry Mason searches for his missing daughter Cheryl as he attempts to unravel the mysterious evil plaguing the town.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15980792-gargoyles-quest-game-boy-use-the-block-buster-to-bust-blocks.png',
    title: "Gargoyle's Quest",
    year: 1990,
    system: 'GB',
    developer: 'Capcom',
    genre: 'Platformer',
    timeToBeat: 4,
    description:
      "Play as Firebrand, one of the antagonists of Ghosts 'n Goblins, and save the Ghoul Realm from the Destroyers!",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15776935-pokemon-mystery-dungeon-red-rescue-team-game-boy-advance-water-g.png',
    title: 'Pokemon Mystery Dungeon: Red Rescue Team',
    year: 2005,
    system: 'GBA',
    developer: 'GameFreak/Chunsoft',
    genre: 'Roguelite',
    timeToBeat: 20,
    description:
      'Take on the role of an actual Pokemon as you team up to start a rescue business and end up discovering a bigger threat than just some lost Pokemon.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/120407-final-fantasy-tactics-playstation-examining-your-opponent-is-a-g.png',
    title: 'Final Fantasy Tactics',
    year: 1997,
    system: 'PS1',
    developer: 'Square',
    genre: 'SRPG',
    timeToBeat: 40,
    description:
      "Final Fantasy's first take on the SRPG genre follows Ramza Beoulve and the situations surrounding him as he learns the truth behind the Zodiac Brave Story in this epic, sprawling adventure; story twists around every corner as friend becomes foe and fable becomes reality.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/2019130-mega-man-x-snes-every-stage-begins-naturally-with-the-introducti.png',
    title: 'Mega Man X',
    year: 1993,
    system: 'SNES',
    developer: 'Capcom',
    genre: 'Platformer',
    timeToBeat: 4,
    description:
      "This is very favorite Mega Man game. The music. The mechanics. The characters. The bosses. Everything about it I vibed with back in '93, and still to this day!",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16324344-dive-alert-beckys-version-neo-geo-pocket-color-becky-is-bored.png',
    title: 'Dive Alert',
    year: 2000,
    system: 'NGPC',
    developer: 'Sacnoth',
    genre: 'RPG',
    timeToBeat: 6,
    description:
      'Interesting little cross of JRPG and Submarine combat featuring a "Pokemon Red and Blue" style Matt or Becky version.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16220070-legend-of-the-river-king-gb-game-boy-color-town-and-options.png',
    title: 'Legend of the River King',
    year: 1997,
    system: 'GBC',
    developer: 'Marvellous',
    genre: 'Fishing/RPG',
    timeToBeat: 6,
    description:
      'A young boy (you) must catch the Guardian Fish to use its magical powers to cure your sister from a mysterious illness.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15747519-pirates-gold-genesis-buying-a-map.png',
    title: 'Pirates! Gold',
    year: 1993,
    system: 'Genesis/Megadrive',
    developer: 'MicroProse',
    genre: 'ARPG',
    timeToBeat: 20,
    description:
      'The player can play as a pirate, privateer, or a pirate hunter.  It features sword fighting, ocean-faring battles, and land battles as its three main arenas of action, connected by role-playing which allows the player to court the favor of local politicos, romance women, and recruit pirates in the local pub.  Players have the opportunity to go on quests, but must also strategically plan raiding excursions and trading routes.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16280249-jet-grind-radio-android-what-tear-gas.png',
    title: 'Jet Set Radio',
    year: 2000,
    system: 'Dreamcast',
    developer: 'Smilebit',
    genre: '3D Action Platformer',
    timeToBeat: 7,
    description:
      'Newly developed Netrium-powered inline skates enable Rudies, self-expression loving, spray-painting vandals to shred, paint, and thwart both rival gangs and the Rokkaku police in this amazing looking, sounding, and playing cult classic.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16645318-parappa-the-rapper-playstation-teaching-you-how-to-sell-at-the-f.png',
    title: 'Parappa the Rapper',
    year: 1996,
    system: 'PS1',
    developer: 'NanaOn-Sha',
    genre: 'Music Rhythm',
    timeToBeat: 2,
    description:
      "One of the stranger games of all time. Rap your way through it and win SunnyFunny's heart.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16501930-sonic-the-hedgehog-2-windows-under-the-water.png',
    title: 'Sonic the Hedgehog 2',
    year: 1992,
    system: 'Genesis',
    developer: 'Sega',
    genre: 'Platformer',
    timeToBeat: 3,
    description:
      'Sonic the Hedgehog 2 is a 1992 platform game developed and published by Sega for the Sega Genesis. It follows Sonic as he attempts to stop Doctor Robotnik from stealing the Chaos Emeralds to power his space station. All while listening to a banger of a (sound)track!',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15934321-mother-3-game-boy-advance-flint-wakes-up.png',
    title: 'Mother 3',
    year: 2006,
    system: 'GBA',
    developer: 'Brownie Brown, HAL Laboratory',
    genre: 'RPG',
    timeToBeat: 27,
    description:
      "A follow-up to the iconic Mother sequel Earthbound, this cult classic was only released in Japan, ported to the Wii U in 2016. Lucas and friends' cult classic adventure has been the subject of many a gaming discussion and is one of the most requested games for English localization.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/7426891-dr-slump-arcadia-2001-title-screen.png',
    title: 'Dr. Slump',
    year: 1999,
    system: 'PS1',
    developer: 'Bandai',
    genre: 'Action-Adventure',
    timeToBeat: Number.MAX_SAFE_INTEGER,
    description:
      'Dr. Slump is an action-adventure game based on the manga and anime series by Akira Toriyama of Dragon Ball fame. It received its first English fan translation two months ago!',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1198721-sweet-home-nes-its-dark-in-here.png',
    title: 'Sweet Home',
    year: 1989,
    system: 'NES',
    developer: 'Capcom',
    genre: 'RPG',
    timeToBeat: 8,
    description:
      "An NES movie-game based on the film of the same name. This game mixes turn-based RPG mechanics and survival horror, requiring you to explore a haunted mansion, mixing and matching each character's unique tool to solve puzzles and come out unscathed. Developed by none other than Capcom, this game served as the main inspiration for Resident Evil, and may in fact be the first Survival Horror game.",
  },
  {
    img: 'https://1.bp.blogspot.com/-Qqs9iaX9HVs/X8fGsDQgXwI/AAAAAAAAF_A/XdLSQHrcg20_imZRDZlJH5cOmj39nfFkwCLcBGAsYHQ/s240/pokemon-unbound-1.png',
    title: 'Pokemon Unbound',
    year: 2004,
    system: 'GBA',
    developer: 'Skeli',
    genre: 'RPG',
    timeToBeat: 20,
    description:
      'Pokemon Unbound features updated graphics, difficulty modes, a unique mission system, character customization, daily events, a rich OST as well as a wide variety of pokemon from gen1-7.',
  },
  {
    img: 'https://n64today.com/wp-content/uploads/2020/07/legend-of-zelda-missing-link-n64-kokiri-forest.jpg',
    title: 'The Legend of Zelda: The Missing Link',
    year: 1998,
    system: 'N64',
    developer: 'Kaze Emanuar',
    genre: 'Action-Adventure',
    timeToBeat: 3,
    description:
      "This mini adventure is set between Ocarina of Time and Majora's Mask as the Hero of Time searches for his missing fairy, Navi. Experience new environments, music, graphics, items and mechanics on this highly acclaimed adventure.",
  },
  {
    img: 'https://www.vizzed.com/vizzedboard/retro/user_screenshots/saves28/284139/NES--Super%20Mario%20Bros%203Mix_Jun24%209_40_42.png',
    title: 'Super Mario Bros. 3Mix',
    year: 1988,
    system: 'NES',
    developer: 'Southbird',
    genre: 'Platformer',
    timeToBeat: 10,
    description:
      'Super Mario 3 Mix takes the best bits of modern Mario games and back ports them so smoothly to the NES that it makes you wonder what the series could have become in an alternate universe.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15788445-dino-crisis-2-playstation-dylan-killing-three-dinos-near-the-jee.png',
    title: 'Dino Crisis 2',
    year: 2000,
    system: 'PS1',
    developer: 'Capcom Production Studio 4',
    genre: 'Action-Adventure',
    timeToBeat: 6,
    description:
      'Run and Gun!? Dino Crisis 2 is where the franchise gains its own identity, and becomes much more action-focused than its zombie mansion sibling. More importantly, DC2 came out in 2000, which means it gets to help fill out the Modern category!',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10532321-diddy-kong-racing-nintendo-64-the-plane-can-also-use-ground-turb.jpg',
    title: 'Diddy Kong Racing',
    year: 1997,
    system: 'N64',
    developer: 'Rare',
    genre: 'Racing',
    timeToBeat: 14,
    description:
      'Choose one of your favorite Rare characters and race a Dinosaur and other animals! Balloons are a delicacy that help you defeat an Evil Pig.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10398588-super-mario-world-2-yoshis-island-snes-the-story-begins.jpg',
    title: "Super Mario World 2: Yoshi's Island",
    year: 1995,
    system: 'SNES',
    developer: 'Nintendo',
    genre: 'Platformer',
    timeToBeat: 8,
    description:
      "Baby Mario fell from the Sky and landed in the safe hands of the Yoshis. BUT OH NO! Baby Bowser's minions captured Baby Luigi and its your mission to save him! Beware! The minions will still try to capture Baby Mario.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16590974-stardew-valley-android-my-farm-is-overgrown-with-grass-rocks-and.png',
    title: 'Stardew Valley',
    year: 2016,
    system: 'Android',
    developer: 'Concerned Ape',
    genre: 'Simulation',
    timeToBeat: 53,
    description:
      "Players take the role of a character who takes over their deceased grandfather's dilapidated farm in a place known as Stardew Valley. The game is open-ended, allowing players to take on activities such as growing crops, raising livestock, crafting goods, mining for ores, selling produce, and socializing with the townspeople, including marriage and having children. It also allows up to three other players to play together online.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/3985143-harvest-moon-64-nintendo-64-this-is-what-happens-when-you-forget.jpg',
    title: 'Harvest Moon 64',
    year: 1999,
    system: 'N64',
    developer: 'Natsume',
    genre: 'Farm Simulation',
    timeToBeat: 44,
    description:
      'My personal favorite of the original Harvest Moon series. Farming, ranching, and romance. Getting married and starting a family is a key component.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15882638-actraiser-snes-deadly-spikes-and-moving-platforms.png',
    title: 'ActRaiser',
    year: 1991,
    system: 'SNES',
    developer: 'Quintet',
    genre: 'Platformer/City Sim',
    timeToBeat: 5,
    description:
      'An animal-raising game where the animal...is MAN. In ActRaiser, you play The Master - or "God" in the original translation. Your god duties are divided into two parts: Side scrolling monster slaying, and top down sim-lite civilization growth. As a side scroller, you possess a statue and go around shredding monsters that might threaten your fledgling human society. When you\'re not killing monsters, you are observing your civilization from above, helping the humans thrive. Beginning with just two humans, you protect their cities from monsters (through weird semi-shmup gameplay), direct their roads and city construction, and receive offerings which you then use to benefit other humans.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/9785790-shin-megami-tensei-persona-3-portable-psp-nope-it-sure-wasnt-how.jpg',
    title: 'Persona 3 portable',
    year: 2009,
    system: 'PSP',
    developer: 'Atlus',
    genre: 'Role-Playing',
    timeToBeat: 66.5,
    description:
      'Greatest JRPG of all time, but on a handheld, now starring a female protagonist, featuring some of the greatest game music, story and characters of its era.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10199990-final-fantasy-viii-windows-our-hero-up-close-and-personal-in-act.jpg',
    title: 'Final Fantasy VIII',
    year: 1999,
    system: 'PS1',
    developer: 'Squaresoft',
    genre: 'RPG',
    timeToBeat: 41,
    description:
      'Set on an unnamed fantasy world with science fiction elements, the game follows a group of young mercenaries, led by Squall Leonhart, as they are drawn into a conflict sparked by Ultimecia, a sorceress from the future who wishes to compress time. During the quest to defeat Ultimecia, Squall struggles with his role as leader and develops a romance with one of his comrades',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/2804488-super-mario-world-snes-between-a-rock-and-a-molten-rock-in-a-cas.png',
    title: 'Super Mario World',
    year: 1990,
    system: 'SNES',
    developer: 'Nintendo',
    genre: 'Platformer',
    timeToBeat: 5,
    description:
      'A plumber named Mario and his brother Luigi along with their new friend yoshi travel through the Mushroom Kingdom to save the princess from the evil Bowser. Plumber brothers Mario and Luigi from Brooklyn have just arrived in an outlandish realm called the Mushroom Kingdom. It was ruled by Princess Toadstool and her faithful Mushroom people.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15704047-spongebob-squarepants-revenge-of-the-flying-dutchman-playstation.png',
    title: 'Spongebob Squarepants - Revenge of the Flying Dutchman',
    year: 2002,
    system: 'GBA',
    developer: 'THQ',
    genre: 'Platformer',
    timeToBeat: 5,
    description:
      "Is it a good game... kinda, sure? It's like the game devs were thinking what kinda insanely difficult borderline assholish things can we throw in every corner of every level, you're never not getting absolutely pummeled by enemies! Everything is out to get you, you can be killed by a damn tumbleweed. What makes it worse is every time Spongebob gets hit he makes the most loud guttural sound imaginable.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16355781-earthworm-jim-3d-nintendo-64-dialogue-with-green-blob.png',
    title: 'Earthworm Jim 3D',
    year: 1999,
    system: 'N64',
    developer: 'VIS Interactive',
    genre: 'Platformer',
    timeToBeat: 9,
    description:
      "Earthworm Jim was one of my fave games to play as a kid. The 3D version always had me cracking up though as he gets knocked out and put into a coma by a cow, then has to battle through his own subconcious, battling all of his fears. This version wasn't by any means the best in the series, in fact, they tend to say it was the downfall of the series itself, but I still always enjoyed it.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1032073-silver-surfer-nes-an-assault-of-ghosts-upon-the-silver-surfer.png',
    title: 'Silver Surfer',
    year: 1990,
    system: 'NES',
    developer: 'Software Creations',
    genre: 'Scrolling Shooter',
    timeToBeat: 1,
    description:
      "Okay, hear me out; this game is actually really good and unironically one of me and a couple of my friend's favorites. Is it very hard? Yes. Is it borderline unfair at times? Yes. Is it beatable? Also yes (and I have!). Behind this frustrating game is actually a very competent shoot 'em up with powerups that change the direction of your shot and a collection of both top down and side scrolling stages. If you persevere and get into a groove and begin memorizing stage hazards, there's a lot of fun to be had in this one. Oh, and the music is composed by musical genius Tim Follin.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15795137-metroid-fusion-game-boy-advance-first-boss-fight.png',
    title: 'Metroid Fusion',
    year: 2002,
    system: 'GBA',
    developer: 'Nintendo',
    genre: 'Metroidvania',
    timeToBeat: 5,
    description:
      "As the latest entry (chronologically) in the Metroid series, Samus has taken on countless enemies that would make the most daring of warriors quake in their space boots... not this bounty hunter... not until now, for what foe could possibly stand toe-to-toe with the galaxies best bounty hunter... but an evil parasite that has taken the shape and characteristics of Samus herself. Now the world of SR388 NAY! THE GALAXY is at a teetering point between safety... and peril, and the only one to weigh the scales in its favor... is Samus 'MF' Aran.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15684955-donkey-kong-country-3-dixie-kongs-double-trouble-game-boy-advanc.png',
    title: "Donkey Kong Country 3: Dixie Kong's Double Trouble",
    year: 1996,
    system: 'SNES',
    developer: 'Rare',
    genre: 'Platformer',
    timeToBeat: 5,
    description:
      "Released midway through the SNES lifecycle, this platformer pushes the hardware capabilities while also building on the already-great gameplay of earlier DK titles. The plot revolves around Dixie Kong and her cousin, Kiddy Kong, in their attempts to rescue the kidnapped Donkey Kong and Diddy Kong from the series' antagonist King K. Rool.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/3359493-streets-of-rage-genesis-player-2s-special-attack-note-that-in-a-.png',
    title: 'Streets of Rage (Bare Knuckle)',
    year: 1991,
    system: 'Mega Drive',
    developer: 'Sega',
    genre: "Beat 'em up",
    timeToBeat: 1.5,
    description:
      "What to say about the penultimate side-scrolling beat 'em up? Streets of Rage is a fantastic game, well designed and beautifully realised. It's glittering streets pop with colour, but trash is piled high on every corner. The game tasks no nonsense Police Officer Blaze Fielding (and two other nameless dudebros) with cleaning the filth, and clearing the trash from the streets of Wood Oak City, one punk's face at a time!",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16040575-castlevania-aria-of-sorrow-game-boy-advance-save-point.png',
    title: 'Castlevania: Aria of Sorrow',
    year: 2003,
    system: 'Game Boy Advance',
    developer: 'Konami',
    genre: 'Metroidvania',
    timeToBeat: 7,
    description:
      "Aria of Sorrow is a 2D Castlevania where you follow Soma Cruz, a teenager granted occult power as a result of being a potential vessel of Dracula's reincarnation, as he battles dark figures that wish to inherit the undead lord's power.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10340990-parasite-eve-playstation-dialogues-in-pe-are-sure-better-than-th.jpg',
    title: 'Parasite Eve',
    year: 1998,
    system: 'PlayStation',
    developer: 'SquareSoft',
    genre: 'Action RPG',
    timeToBeat: 9.5,
    description:
      "The year is 1998. Officer Aya Brea discovers that a woman with the ability to make people spontaneously combust is hell-bent on destroying the human race, one flaming pile at a time... except Aya, who seems to be immune and, in fact... has some powers of her own. Horrifying hallways and blood stained corpses stacked one after another with relentless enemies and puzzles, this game borrows the best of Resident Evil while adding in its own RPG strategic combat system. Aya's in the business of killin' monsters.... and business is good...",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15999636-clock-tower-snes-scissorman.png',
    title: 'Clock Tower',
    year: 1995,
    system: 'SNES',
    developer: 'Human Entertainment',
    genre: 'Point-and-click adventure',
    timeToBeat: 2.5,
    description:
      "Clock Tower is a survival horror point-and-click adventure game developed and published by Human Entertainment for the Super Famicom in 1995. It is the first installment in the Clock Tower series. You're a girl on the run for a madman wielding scissors. Truly terrifying despite it being 2D. Clocktower still manages to frighten.",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16909103-the-legend-of-zelda-oracle-of-seasons-game-boy-color-in-the-gang.png',
    title: 'The Legend of Zelda: Oracle of Seasons',
    year: 2001,
    system: 'Game Boy Color',
    developer: 'Nintendo',
    genre: 'Action-adventure',
    timeToBeat: 15.5,
    description:
      'In Oracle of Seasons, players traverse the seasons and unlock the secrets of Hyrule held within each climate. Originally intended as a direct port of the original Legend of Zelda to the Game Boy Color, this title\'s development expanded into something greater, standing as an interconnected entry with the Oracle of Ages. Featuring both gorgeous visuals and depth far beyond that of the original NES entry, it was well-deserving of IGN\'s proclamation that both it and its counterpart were "the best games ever made for the Game Boy Color".',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16480375-wild-arms-playstation-battle-on-the-world-map-in-the-middle-of-t.png',
    title: 'Wild Arms',
    year: 1996,
    system: 'PlayStation',
    developer: 'Media.Vision',
    genre: 'RPG',
    timeToBeat: 29,
    description:
      "While FFVII evolved the JRPG genre on the PlayStation 1, Wild Arms took tropes that were already present and elevated them. There's turn-based battles, Zelda-like puzzles and one of the most amazing soundtracks ever to have graced this genre. And did I mention it's a freaking western?",
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/15748254-policenauts-sega-saturn-ed-ms-karen.png',
    title: 'Policenauts',
    year: 1994,
    system: 'PlayStation',
    developer: 'Konami',
    genre: 'Visual Novel',
    timeToBeat: 11.5,
    description:
      'Before Konami\'s Metal Gear Solid took the PlayStation by storm, its creator - Hideo Kojima - explored his cinematic ambitions for gaming in a very different form: an endlessly stylish cyberpunk adventure game. Jonathon Ingram, one of five "Policenauts", wakes up 28 years after a spacewalk gone wrong to discover that his team has succeeded. Now, mankind lives among the stars.',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/16306120-advance-wars-2-black-hole-rising-game-boy-advance-capture-the-bu.png',
    title: 'Advance Wars 2: Black Hole Rising',
    year: 2001,
    system: 'Nintendo Gameboy Advance',
    developer: '',
    genre: '',
    timeToBeat: Number.MAX_SAFE_INTEGER,
    description: '',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/10781853-super-mario-64-nintendo-64-inside-the-castle.jpg',
    title: 'Super Mario 64',
    year: 1996,
    system: 'Nintendo 64',
    developer: '',
    genre: '',
    timeToBeat: Number.MAX_SAFE_INTEGER,
    description: '',
  },
  {
    img: 'https://cdn.mobygames.com/screenshots/1242542-chrono-trigger-snes-map-ad.png',
    title: 'Chrono Trigger',
    year: 1995,
    system: 'Super Nintendo',
    developer: '',
    genre: '',
    timeToBeat: Number.MAX_SAFE_INTEGER,
    description: '',
  },
];
