import { GameData } from '../models/gameData.model';

export const retrobits: GameData[] = [
  {
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/957401119619948605/Retro_Bits_01_-_Bomberman.gif',
    title: { usa: 'Bomberman' },
    year: 1990,
    system: 'TG-16/PCE',
    developer: 'Hudson',
    genre: 'puzzle',
    timeToBeat: 2,
    description:
      "Join White Bomberman in a reimagining of his original arcade release as he places bombs to deal with foes and save his creator's daughter from the clutches of Black Bormebrman! A classic puzzle game that's fun for everyone!",
  },
  {
    title: { usa: 'Pahalanx: The Enforce Fighter A-144' },
    year: 1992,
    system: 'SNES, GBA',
    developer: 'Kemco',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      "Everyone remembers this game for the unfitting, but kindly old man on the cover of this epic, frantic, spaceship shoot'em up. Swap between weapons on the fly or sacrifice them ot perform powerful special moves!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/959965544700850226/Retro_Bits_02_-_Phalanx.gif',
  },
  {
    title: { usa: 'Alien Storm' },
    year: 1990,
    system: 'Arcade/Genesis',
    developer: 'Sega',
    genre: "Beat'em Up",
    timeToBeat: 2,
    description:
      'A homicidal alien race is invading the Earth, and the only thing that stands between them and world domination are a special forces team known as the "Alien Busters"! A unique beat\'em up with 3PS and shmup style sections!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/962502522927456296/Retro_Bits_03_-_Alien_Storm.gif',
  },
  {
    title: { usa: 'The Last Blade' },
    year: 1997,
    system: 'Neo Geo',
    developer: 'SNK',
    genre: 'Fighting',
    timeToBeat: 2,
    description:
      'After the success of Samurai Showdown, SNK took another stab at a 2D weapon-based fighter. Though not garnering as much attention as other SNK titles, The Last Blade has become something of a fighting game cult classic.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/965043476871913482/Retro_Bits_04_-_The_Last_Blade.gif',
  },
  {
    title: { usa: 'Night Striker' },
    year: 1989,
    system: 'Arcade/PS1',
    developer: 'Taito',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      "What if Outrun was a futuristic shoot'em up and your car could fly? In Night Striker, take to the skies and streets, blast foes, and at the end of each stage, your path will determine which level you'll see next, and your ending!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/967576050185936966/Retro_Bits_05_-_Night_Striker.gif',
  },
  {
    title: { usa: 'Rocket Knight Adventures' },
    year: 1993,
    system: 'Sega Genesis/MD',
    developer: 'Konami',
    genre: 'Action-Platformer',
    timeToBeat: 2,
    description:
      'The first adventrue of the bravest opossum rocket knight: Sparkster! Using your sword and jetpack, dash, boost, and slash your way through a multitude of levels to defeat an evil empire of pigs in this cult classic!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/970112413133316096/Retro_Bits_06_-_Rocket_Knight_Adventures.gif',
  },
  {
    title: { usa: 'Friday the 13th' },
    year: 1993,
    system: 'NES',
    developer: 'Atlus',
    genre: 'Survival Horror',
    timeToBeat: 2,
    description:
      'What better time to defeat Jason Voorhees? Shift control between 6 camp counselors at Camp Crystal Lake and try to kill Jason... Before he does the same to you! This cryptic puzzle adventure will surely frighten you...',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/972650896200724510/Retro_Bits_07_-_Friday_the_13th.gif',
  },
  {
    title: { usa: 'Cannon Spike' },
    year: 2000,
    system: 'Arcade, Dreamcast',
    developer: 'Psikyo',
    genre: 'Top-Down Shooter',
    timeToBeat: 2,
    description:
      "Terrorist robots are running rampant! Take control of one of Capcom's familiar faces (or the all-new Simone) and take the fight to them, blasting and attacking while using your motor boots in this unique Dreamcast hidden gem.",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/975185861790539806/Retro_Bits_08_-_Cannon_Spike.gif',
  },
  {
    title: { usa: 'Sonic Advance' },
    year: 2001,
    system: 'GBA',
    developer: 'Dimps',
    genre: 'Platformer',
    timeToBeat: 2,
    description:
      "Dimps' first title, and their first of three attempts to introduce classic Sonic to a new audience with Sonic Adventure-esque flair. Play as Sonic, Tails, Knuckles, or Amy, take down Eggman, and raise a Tiny Chao in between!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/977722623242960906/Retro_Bits_09_-_Sonic_Advance.gif',
  },
  {
    title: { usa: 'Aero Fighters', jap: 'Sonic Wings' },
    year: 1992,
    system: 'Arcade, SNES',
    developer: 'Tecmo',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      'Pick one of four pilots and take flight in 7 different levels, some of which are presented in random order! Each pilot has their own stats, shot pattern, and bomb, so try them all out until one clicks! There are two sequels on Neo Geo!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/980259604422332456/Retro_Bits_10_-_Aero_Fighters_-_Sonic_Wings.gif',
  },
  {
    title: { usa: 'Solstice: The Quest for the Staff of Demnos' },
    year: 1990,
    system: 'NES',
    developer: 'Software Creations',
    genre: 'Puzzle/Adventure',
    timeToBeat: 2,
    description:
      'When the evil baron Morbius captures Princess Eleanor, the wizard Shadax must navigate 250 rooms within the fortress Kastlerock and assemble the six pieces of the Staff of Demnos to defeat him.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/982796151403188264/Retro_Bits_11_-_Solstice.gif',
  },
  {
    title: { usa: 'Super R.C. Pro Am' },
    year: 1991,
    system: 'Game Boy',
    developer: 'Rare',
    genre: 'Racing',
    timeToBeat: 2,
    description:
      'R.C. pro Am in your pocket! Race across 24 different tracks, grabbing upgrades, powerups, and the letters to spell NINTENDO so you can upgrade your R.C. car to the next racing class and win the Nintendo Champion cup!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/985332713970085939/Retro_Bits_12_-_Super_R.C._Pro_Am.gif',
  },
  {
    title: { usa: 'Crossed Swords' },
    year: 1991,
    system: 'Neo Geo, NGCD',
    developer: 'Alpha Denshi',
    genre: "Hack 'n Slash",
    timeToBeat: 2,
    description:
      'Engage in thrilling, over-the-shoulder swordplay, timing your dodging and blocking while countering with strikes of your own! Multiple pathways and an intuitive, yet complex combat system offers plenty of replay value!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/987871302637453412/Retro_Bits_13_-_Crossed_Swords.gif',
  },
  {
    title: { jap: 'SD Hero Soukessen: Taose! Aku no Gundam' },
    year: 1991,
    system: 'Famicom',
    developer: 'Interlink',
    genre: 'Action Platformer',
    timeToBeat: 2,
    description:
      "Team up as SD (super deformed) versions of various characters from Banpresto's Compati Hero series, featuring a crossover between Kamen Rider, Ultraman, Metal Hero, and Gundam as you fight to save Emi!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/990406083157819392/Retro_Bits_14_-_SD_Hero_Soukessen_-_Taose_Aku_no_Gundan.gif',
  },
  {
    title: { usa: 'Dead Moon' },
    year: 1991,
    system: 'TG-16/PCE',
    developer: 'Zap',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      "This Turbografx-16/PC Engine-exclusive shoot'em up takes you through 6 stages. The twist here is that your powerups count as your hit points; take some damage and instead of dying, you'll only lose a powerup.",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/992942834766327938/Retro_Bits_15_-_Dead_Moon.gif',
  },
  {
    title: { usa: 'Alisia Dragoon' },
    year: 1992,
    system: 'Sega Genesis/MD',
    developer: 'Game Arts',
    genre: 'Action Platformer',
    timeToBeat: 2,
    description:
      'Take control of Alisia in a quest to avenge her father and save the world. Alisia can summon lightning from her hands, but must charge it fro maximum effect. Luckily, she has 4 swappable monster allies to watch her back!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/995479576807485440/Retro_Bits_16_-_Alisia_Dragoon.gif',
  },
  {
    title: { usa: 'Star Gladiator - Episode 1: Final Crusade' },
    year: 1996,
    system: 'Arcade, PS1',
    developer: 'Capcom',
    genre: 'Fighting',
    timeToBeat: 2,
    description:
      'Capcoms first in-house polygonal fighter, Star Gladiator is like Soul Calibur with a futuristic aesthetic. Learn how to do Plasma Reverses, Plasma Reflects, and Plasma Combos to defeat the evil Bilstein!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/998016247730032740/Retro_Bits_17_-_Star_Gladiator_-_Episode_1_-_Final_Crusade.gif',
  },
  {
    title: { usa: 'Krazy Kreatures' },
    year: 1990,
    system: 'NES',
    developer: 'Bitmasters',
    genre: 'Puzzle',
    timeToBeat: 2,
    description:
      'An unlicensed puzzle game published by American Video Entertainment Inc, Krazy Kreatures has you klearing kreatures by matching them in rows, kolumns, or diagonals by 3 or more. Simple to learn and great with a friend!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1000553398304784404/Retro_Bits_18_-_Krazy_Kreatures.gif',
  },
  {
    title: { usa: 'Bonks Adventure' },
    year: 1989,
    system: 'TG-16/PCE',
    developer: 'Red Company',
    genre: 'Platformer',
    timeToBeat: 2,
    description:
      'An unlicensed puzzle game published by American Video Entertainment Inc, Krazy Kreatures has you klearing kreatures by matching them in rows, kolumns, or diagonals by 3 or more. Simple to learn and great with a friend!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1003089759444418630/Retro_Bits_19_-_Bonks_Adventure.gif',
  },
  {
    title: { usa: 'Cotton: Fantastic Night Dreams' },
    year: 1991,
    system: 'Arcade, TG-CD',
    developer: 'Success',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      'A key title in the "cute\'em up" genre, Cotton follows the eponymous with as she saves a magical world from a dark mist... In exchange for her favorite candy, of course. Blast foes, cast spells, and get help from fairy allies!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1005626438105444392/Retro_Bits_20_-_Cotton_-_Fantastic_Night_Dreams.gif',
  },
  {
    title: { usa: 'Mighty Morphin Power Rangers: The Fighting Edition' },
    year: 1995,
    system: 'Super Nintendo',
    developer: 'Natsume',
    genre: 'Fighting',
    timeToBeat: 2,
    description:
      'Go go Power Rangers! Take control of your favorite Megazord and do battle with other zords and foes from the beloved franchise. Time your special moves carefully to power up and do even more damage!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1008163936757088306/Retro_Bits_21_-_Mighty_Morphin_Power_Rangers_-_The_Fighting_Edition.gif',
  },
  {
    title: {
      usa: 'Valis',
      jap: 'Mugen Senshi Valis',
      other: 'Valis: The Fantasm Soldier',
    },
    year: 1991,
    system: 'Sega Genesis/MD',
    developer: 'Wolf Team',
    genre: 'Action Platformer',
    timeToBeat: 2,
    description:
      'The Genesis remake of the 1986 MSX title, control schoolgirl Yoko Asou as she is begrudgingly fated to protect the three realms. Slide, jump, slash, and upgrade your sword, defeating bosses to utilize their powerful magics.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1010699842441453608/Retro_Bits_22_-_Valis_-_The_Fantasm_Soldier.gif',
  },
  {
    title: { world: 'Pu Li Ru La' },
    year: 1991,
    system: 'Arcade, PS1, PS2',
    developer: 'Taito',
    genre: "Beat'em Up",
    timeToBeat: 2,
    description:
      "In Radishland, each town has a time key which keeps time flowing regularly. When a bad man shows up and starts stealing time keys, it's up to Zac and Mel and their magic sticks to retrieve the time keys and save Radishland!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1013236508301463582/Retro_Bits_23_-_Pu-Li-Ru-La.gif',
  },
  {
    title: { usa: 'Magical Chase' },
    year: 1991,
    system: 'TG16/PCE, GBC',
    developer: 'Quest',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      "Oops! Witch Ripple has accidentally released six demons from a forbidden tome and now it's up to her and her two star companions, Topsy and Turvy, to stop them, seal them back into the tome, and save the world!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1015773342466318426/Retro_Bits_24_-_Magical_Chase.gif',
  },
  {
    title: { usa: 'Sonic CD' },
    year: 1993,
    system: 'Sega CD, Android',
    developer: 'Sega',
    genre: 'Platformer',
    timeToBeat: 2,
    description:
      "Has sonic finally met his match? Sonic CD introduces Sonic's greatest rival yet: Metal Sonic! The Blue Blur must travel through space and time to try and create a Good Future and to free Little Planet from Robotnik!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1018310716593295430/Retro_Bits_25_-_Sonic_CD.gif',
  },
  {
    title: { usa: 'Cadash' },
    year: 1989,
    system: 'Arcade, TG-16',
    developer: 'Taito',
    genre: 'Action-Adventure',
    timeToBeat: 2,
    description:
      "The demon Balrog has taken over the earth, with the exception of the last human kingdom of Dirzir. When Dirzir's princess is captured, it's up to the four heroes to quest forth and find her in this action adventure arcade RPG!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1020846837831303208/Retro_Bits_26_-_Cadash.gif',
  },
  {
    title: { usa: 'Digimon: Rumble Arena' },
    year: 2001,
    system: 'PS1',
    developer: 'Bandai',
    genre: 'Platform Fighter',
    timeToBeat: 2,
    description:
      'Pick your favorite Digimon from the first 3 seasons of the show and duke it out on a variety of different stages in this Smash Brothers-like platform fighter! Digivolve at opportune times and unleash your special move!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1023383656456265738/Retro_Bits_27_-_Digimon_-_Rumble_Arena.gif',
  },
  {
    title: { usa: "Devil's Crush" },
    year: 1990,
    system: 'TG-16, Genesis',
    developer: 'Compile',
    genre: 'Pinball',
    timeToBeat: 2,
    description:
      "Start spooky season off the right way with the #1 horror virtual pinball game: Devil's Crush! With a free scrolling triple-tiered playfield and many bonus rooms, Devil's Crush is one virtual pinball game you won't soon forget!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1025920105483358238/Retro_Bits_28_-_Devils_Crush.gif',
  },
  {
    title: { usa: 'Splatterhouse' },
    year: 1988,
    system: 'Arcade, TG-16',
    developer: 'Namco',
    genre: "Beat'em Up",
    timeToBeat: 2,
    description:
      'When Rick and his girlfriend Jennifer are trapped inside the infamous Splatterhouse, Rick meets his end while Jennifer is taken away. Resurrected by the Terror Mask, Rick begins a violent, gruesome quest.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1028456868651216916/Retro_Bits_29_-_Splatterhouse.gif',
  },
  {
    title: { usa: "Castlevania II: Belmont's Revenge" },
    year: 1991,
    system: 'Gameboy, GBC',
    developer: 'Konami',
    genre: 'Action-Platformer',
    timeToBeat: 2,
    description:
      "15 years after the events of Castlevania: The Adventure, Dracula kidnaps Christopher Belmont's son Soleil. Featuring a level select system, Chris must head out to stop Dracula once again.",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1030993544611119114/Retro_Bits_30_-_Castlevania_II_-_Belmonts_Revenge.gif',
  },
  {
    title: { usa: 'Haunting: Starring Polterguy' },
    year: 1993,
    system: 'Genesis/MD, PSP',
    developer: 'Electronic Arts',
    genre: 'Action',
    timeToBeat: 2,
    description:
      "Those slimy Sardinis! Tehy think they got the last laugh on Polterguy by selling him a janky skateboard, but he's gonna have th elast laugh! Possess objects around the Sardini's homes and really teach them a lesson!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1033530450989305926/Retro_Bits_31_-_Haunting_Starring_Polterguy.gif',
  },
  {
    title: { usa: 'Darkstalkers: The Night Warriors' },
    year: 1994,
    system: 'Arcade, PS1, PS2',
    developer: 'Capcom',
    genre: 'Fighting',
    timeToBeat: 2,
    description:
      "THE premier horror-themed 2D fighting game! As any number of classic montsers, stop the evil alien Pyron on his quest to devour Earth. Humankind stands no chance, so now it's up to the monsters to step up!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1036067001191370822/Retro_Bits_32_-_Darkstalkers_-_The_Night_Warriors.gif',
  },
  {
    title: { usa: 'Hagane: The Final Conflict' },
    year: 1994,
    system: 'SNES',
    developer: 'CAProduction',
    genre: 'Action-Platformer',
    timeToBeat: 2,
    description:
      'Reborn as a cyborg ninja, Hagane must take revenge on an enemy ninja clan. With four different weapons to swap through, air-dashes, wall-clings, and more, Hagane has all the tools he needs at his disposal.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1038919527104262184/Retro_Bits_33_-_Hagane_-_The_Final_Conflict.gif',
  },
  {
    title: { usa: 'Metal Slug: 1st Mission' },
    year: 1999,
    system: 'NGPC, Switch, PC',
    developer: 'Ukiyotei',
    genre: "Run'n Gun",
    timeToBeat: 2,
    description:
      "Love Metal Slug? How about some Metal Slug in your pocket! This tiny Metal Slug features all the things you know and love about the popular run'n gun franchise, turned tiny! Find powerups, multiple paths, and pilot machines!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1041155565151322113/Retro_Bits_34_-_Metal_Slug_-_1st_Mission.gif',
  },
  {
    title: { usa: 'Blazing Star' },
    year: 1998,
    system: 'Neo Geo',
    developer: 'Yumekobo',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      "The follow-up to Pulstar, Blazing star improves on the shoot'em up formula by offering combos the player can pull off by mashing the B button during a powered up shot. Collect powerups and try different machines!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1043692321717370890/Retro_Bits_35_-_Blazing_Star.gif',
  },
  {
    title: { jap: 'Cocoron' },
    year: 1991,
    system: 'Famicom',
    developer: 'K2, Takeru',
    genre: 'Action-Platformer',
    timeToBeat: 2,
    description:
      "When the princess of the dream land is kidnapped, it's up to you to save her. Tapir will let you choose any form in your dream, so create a character and use each part's unique strengths to save the princess!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1046228924377608282/Retro_Bits_36_-_Cocoron.gif',
  },
  {
    title: { usa: 'Snow Bros' },
    year: 1990,
    system: 'Arcade, NES, GB',
    developer: 'Toaplan',
    genre: 'Action',
    timeToBeat: 2,
    description:
      "When the twin princesses are captured, it's up to Nick and Tom to use their snowy powers to save the day! In this Bubble Bobble-like, defeat enemies by turning them into sonwballs, then rolling them into each other!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1048765773826502727/Retro_Bits_37_-_Snow_Bros.gif',
  },
  {
    title: { usa: 'Elf Bowling' },
    year: 1998,
    system: 'PC, GBA, DS',
    developer: 'NStorm',
    genre: 'Sports',
    timeToBeat: 2,
    description:
      "When Santa's elves go on strike due to overworking for high demands of Christmas toys, Santa has to find a way to whip them back into shape! The elves may be on strike, but Santa will get a few strikes of his own!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1051302401300238356/Retro_Bits_38_-_Elf_Bowling.gif',
  },
  {
    title: { usa: 'Santa Claus Junior' },
    year: 2001,
    system: 'Game Boy Color',
    developer: 'NEON Software',
    genre: 'Platformer',
    timeToBeat: 2,
    description:
      "When Santa gets zapped and kidnapped by an evil witch, it's up to little Nick to find the missing presents, defeat the witch, and rescue everyone's favorite Claus. If this won't get you int othe holiday spirit, nothing will.",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1053839193979240498/Retro_Bits_39_-_Santa_Claus_Junior.gif',
  },
  {
    title: { usa: 'Kickle Cubicle' },
    year: 1998,
    system: 'Arcade, NES',
    developer: 'IREM',
    genre: 'Puzzle',
    timeToBeat: 2,
    description:
      "One day, Kickle wakes up to find his entire homeland, the Fantasy Kingdom, has been turned to ice by the evil Wicked Wizard King. With Kickle's ice breath attack, he sets out to collect the red Dream Bags and save the day!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1056375795414741032/Retro_Bits_40_-_Kickle_Cubicle.gif',
  },
  {
    title: { usa: 'Unholy Night: The Darkness Hunter' },
    year: 2017,
    system: 'SNES',
    developer: 'Foxbat Corporation',
    genre: 'Fighting',
    timeToBeat: 2,
    description:
      'Unholy Night: The Darkness Hunter is a fighting game created by former members of SNK. When they failed to meet their kickstarter goal, Retroism stepped in to publish it and give this retro 2D fighter a chance.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1058912434682871908/Retro_Bits_41_-_Unholy_Night_-_The_Darkness_Hunter.gif',
  },
  {
    title: { usa: 'Teenage Mutant Ninja Turtles: Fall of the Foot Clan' },
    year: 1990,
    system: 'Game Boy',
    developer: 'Konami',
    genre: 'Action-Platformer',
    timeToBeat: 2,
    description:
      "The first of the Game Boy TMNT games, take control of the turtles to defeat TMNT villains such as Bebop, Rocksteady, Baxter Stockman, Shredder, and Krang, on a quest ot rescue April O'Neil.",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1061449263810347028/Retro_Bits_42_-_TMNT_-_Fall_of_the_Foot_Clan.gif',
  },
  {
    title: { usa: 'Shock Troopers' },
    year: 1997,
    system: 'Neo Geo',
    developer: 'Saurus',
    genre: "Run'n Gun",
    timeToBeat: 2,
    description:
      'Choose one of eight characters, each with their own special weapon, then pick one of three paths to take the fight to the Bloody Scorpions terrorist group who have a deadly plot to steal a drug capable of creating supersoldiers.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1063986102169518160/Retro_Bits_43_-_Shock_Troopers.gif',
  },
  {
    title: { usa: 'Um Jammer Lammy' },
    year: 1999,
    system: 'PS1, Arcade',
    developer: 'NanaOn-Sha',
    genre: 'Music-Rhythm',
    timeToBeat: 2,
    description:
      'Leave it to Lammy! In this sequel/spiritual successor to PaRappa the Rapper, take control of anxiety-ridden guitarist Lammy of band Milk Can as she tries to make it to her shouw, but not before a TON of shenanigans!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1066522654963667114/Retro_Bits_44_-_Um_Jammer_Lammy.gif',
  },
  {
    title: { jap: 'SD the Great Battle: Aratanaru Chousen' },
    year: 1990,
    system: 'Super Famicom',
    developer: 'Banpresto',
    genre: 'Action',
    timeToBeat: 2,
    description:
      'When the climate control system on SD island went haywire, evil creatures started appearing. V3, Taro, and Knight Gundam went out to investigate but never returned... Can Rider 1, Ultraman, and Gundam save the day?',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1069059366210256916/Retro_Bits_45_-_SD_the_Great_Battle_-_Aratanaru_Chousen.gif',
  },
  {
    title: { usa: 'Contra', jap: 'Gryzor', eu: 'Probotector' },
    year: 1986,
    system: 'Arcade, NES',
    developer: 'Konami',
    genre: 'Run`n Gun',
    timeToBeat: 2,
    description:
      "The original run'n gun that all others nstrive for! Take control of Lance or Bill and take out the evil Red Falcon Organization's secret island base! Don't forget your Konami Code; you might need those extra 30 lives!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1071597231083356280/Retro_Bits_46_-_Contra.gif',
  },
  {
    title: { usa: 'Balloon Kid' },
    year: 1990,
    system: 'Game Boy',
    developer: 'Nintendo R&D1',
    genre: 'Flying Platformer',
    timeToBeat: 2,
    description:
      'The sequel to Balloon Fight, take control of Alice on a journey to save the hero of Balloon Fight, complete with stages, bosses, and the ability to detach your balloons and inflate new ones! Go, Balloon Kid!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1074132827257446491/Retro_Bits_47_-_Balloon_Kid.gif',
  },
  {
    title: { usa: 'Chocobo Racing' },
    year: 1999,
    system: 'Playstation',
    developer: 'Squaresoft',
    genre: 'Racing',
    timeToBeat: 2,
    description:
      "Wark! Now's your chance to race with classic Squaresoft characters! Play the story mode and hepl Chocobo as he tries to win the pieces of the legendary Blue Crystal from the other racers. Kweh!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1076669676551147530/Retro_Bits_48_-_Chocobo_Racing.gif',
  },
  {
    title: { jap: 'Magical Taruruuto-Kun' },
    year: 1991,
    system: 'Sega Game Gear',
    developer: 'Tsukuda Ideal',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      "Fly through 6 stages in this cute'em up based on the manga of the same name. Taruruuto-kun has a tendency to turn objects into sentient creatures, so you'll have to fix his mistakes! Get some powerups and blast away!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1079206279156871219/Retro_Bits_49_-_Magical_Taruruuto-kun.gif',
  },
  {
    title: { usa: 'Gaiaopolis' },
    year: 1993,
    system: 'Arcade',
    developer: 'Konami',
    genre: "AARPG/Beat'em Up",
    timeToBeat: 2,
    description:
      'Take control of the Prince, Fairy, or Dragon and quest across the land to find the three keys so you can prevent the King of Darkness from resurrecting an ancient demon. Beat montsers, level up, save the world!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1081743385313951855/Retro_Bits_50_-_Gaiapolis.gif',
  },
  {
    title: { usa: "Spanky's Quest" },
    year: 1991,
    system: 'SNES',
    developer: 'Natsume',
    genre: 'Action',
    timeToBeat: 2,
    description:
      'The evil witch Morticia has trapped Spanky in a tower guarded by her magical fruit minions! Use your wits and balls from various sports to defeat enemies, collect keys, battle Morticia, and escape her tower!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1084279703612969000/Retro_Bits_51_-_Spankys_Quest.gif',
  },
  {
    title: { usa: 'Space Channel 5' },
    year: 1999,
    system: 'Sega Dreamcast',
    developer: 'Sega',
    genre: 'Music/Rhythm',
    timeToBeat: 2,
    description:
      "This just in: Aliens are invading Earth and forcing Earthlings to... Dance? Stay tuned to Space Channel 5 to find out all of developments, featuring our star reporter: Ulala! She'll dance to save the day!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1086802201785143386/Retro_Bits_52_-_Space_Channel_5.gif',
  },
  {
    title: { usa: 'Prehistoric Isle in 1930' },
    year: 1989,
    system: 'Arcade',
    developer: 'SNK',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      'In the 1930s, ships sailing near the Bahamas have been mysteriously going missing. The U.S. Marines send out a search party and discover Greenhell Isle, populated by dinosaurs, long though to be extinct! Well, they will be!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1089338006676193310/Retro_Bits_53_-_Prehistoric_Isle_in_1930.gif',
  },
  {
    title: { usa: 'Sonic Chaos' },
    year: 1993,
    system: 'Master System',
    developer: 'Aspect Co. Ltd',
    genre: 'Platformer',
    timeToBeat: 2,
    description:
      'Well, looks like Robotnik is back at it again. Having collected all of the Chaos Emeralds, he\'s out to create some sort of nuclear weaponry and it\'s up to our old friends Sonic and Miles "Tails" Prower to take care of him once more.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1091874763892334663/Retro_Bits_54_-_Sonic_Chaos.gif',
  },
  {
    title: { usa: 'The Last Blade: Beyond the Destiny' },
    year: 2000,
    system: 'NGPC',
    developer: 'SNK',
    genre: 'Fighting',
    timeToBeat: 2,
    description:
      'Experience the Last Blade in the palm of your hand, then put it in your pocket! In this Neo Geo Pokcet Color rendition of The Last Blade, complete story mode and collect endings and gallery scrolls fro some nice replay value.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1094412140846272562/Retro_Bits_55_-_The_Last_Blade_-_Beyond_the_Destiny.gif',
  },
  {
    title: { usa: 'Deadeus' },
    year: 2019,
    system: 'Game boy',
    developer: '-IZMA-',
    genre: 'Horror',
    timeToBeat: 2,
    description:
      'Deadeus centers around a small boy who has a prophetic nightmare telling him everyone will die in 3 days and that he has to investigate his village to see how he can save them, if at all. Deadeus has 11 endings and no direct path.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1096948135340802118/Retro_Bits_56_-_Deadeus.png',
  },
  {
    title: { usa: 'Mystic Riders' },
    year: 1992,
    system: 'Arcade',
    developer: 'Irem Corp.',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      "Grab your broom and take to the skies in this cute'em up! Features powerups and the ability to throw and swing your broom to block projectiles, as well as seamlessly transitioning from flying to run and gun style segments!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1099484890061349004/Retro_Bits_57_-_Mystic_Riders.gif',
  },
  {
    title: { usa: 'Inspector Gadget' },
    year: 1993,
    system: 'SNES',
    developer: 'AIM',
    genre: 'Platformer',
    timeToBeat: 2,
    description:
      'Oh no! Penny has been kidnapped by Dr. Claw and his MAD soldiers! Good thing Gadget is on the case! Use a wide variety of gadgets to tackle platforming challenges in a plethora of interesting and unique ways!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1102021591937843290/Retro_Bits_58_-_Inspector_Gadget.gif',
  },
  {
    title: { usa: 'River City Ransom', jap: 'Street Gangs' },
    year: 1989,
    system: 'NES',
    developer: 'Technos Japan',
    genre: "Beat'em Up/ARPG",
    timeToBeat: 2,
    description:
      "When Ryan's girlfriend Cyndi is kidnapped by local gang leader Slick, it's up to Ryan and his friend Alex to beat up the thugs and save her! Features RPG elements, like increasing your stats by buing items and learning new attacks!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1104558367986430012/Retro_Bits_59_-_River_City_Ransom.gif',
  },
  {
    title: { usa: 'NARC' },
    year: 1988,
    system: 'Arcade, NES',
    developer: 'Williams Electronics',
    genre: "Run'n Gun",
    timeToBeat: 2,
    description:
      "Winners don't use drugs! As Max Force and Hit Man, take teh war on drugs to the streets as you attempt to bust king pin Mr. Big and his plethora of drug selling lackies! Pakcing a rifle and missile launcher, just say NO!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1107095011654381689/Retro_Bits_60_-_NARC.png',
  },
  {
    title: { usa: 'REZ' },
    year: 2001,
    system: 'Dreamcast, PS2',
    developer: 'United Game Artists',
    genre: 'Rail Shooter',
    timeToBeat: 2,
    description:
      "Follow a hacker's journey into a malfunctioning AI as you blast enemies to the musical beats. The game was designed to emulate synesthesia and share its story via minimal dialogue and instead through thematic references to life.",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1109631698406228019/Retro_Bits_61_-_Rez.gif',
  },
  {
    title: { usa: 'Power Blade' },
    year: 1990,
    system: 'NES',
    developer: 'Taito',
    genre: 'Action-Platformer',
    timeToBeat: 2,
    description:
      'Control Nova and his powerful boomerangs through action-platforming challenges reminiscent of Mega Man! Nova can throw his boomerangs in 8 directions, power them up to fly farther, and throw more!',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1112168505081606195/Retro_Bits_62_Power_Blade.gif',
  },
  {
    title: { usa: 'Fatal Fury: First Contact' },
    year: 1999,
    system: 'NGPC, Switch',
    developer: 'SNK',
    genre: 'Fighting',
    timeToBeat: 2,
    description:
      'Take control of one of 13 King of Fighters characters, in chibi-style of coures, and go punch Geese Howard in his little chibi face! As is true of all the NGPC figthers, you can expect smooth controls and solid sprite work.',
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1114705452928860231/Retro_Bits_63_-_Fatal_Fury_-_First_Contact_.gif',
  },
  {
    title: { usa: 'Boogie Wings', jap: 'The Great Ragtime Show' },
    year: 1992,
    system: 'Arcade',
    developer: 'Data East',
    genre: "Shoot'em Up",
    timeToBeat: 2,
    description:
      "It's time for the Great Ragtime Show! Pilot a biplane with a giant hook attached to grab items, deal damage, and drop bombs on foes! A unique and fun shoot'em up with a World War I mixed with steampun aesthetic.",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1117241848797343864/Retro_Bits_64_-_Boogie_Wings.gif',
  },
  {
    title: { usa: "Disney's Goof Troop" },
    year: 1993,
    system: 'SNES',
    developer: 'Capcom',
    genre: 'Action-Adventure',
    timeToBeat: 2,
    description:
      "The Legend of Zelda meets Disney? Capcom created an amazing multiplayer, Zelda-like experience here, don't let the licencsing fool you! As Max or Goofy, use various tools like grappling hooks to solve puzzles and defeat Pete and his crew!",
    img: 'https://cdn.discordapp.com/attachments/957342297270415480/1119778552787767348/Retro_Bits_65_-_Goof_Troop.gif',
  },
  {
    title: { jap: 'Ghost Sweeper Mikami: Joreishi wa Nice Body' },
    year: 1993,
    system: 'Super Nintendo',
    developer: 'Natsume',
    genre: 'Action-Platformer',
    img: 'https://media.discordapp.net/attachments/957342297270415480/1122315465386106890/Retro_Bits_66_-_Ghost_Sweeper_Mikami_-_Joreishi_wa_Nice_Body.gif',
    description:
      'Based on the manga and anime series Ghost Sweeper Mikami, take control of Reiki, the exorcist with the  "Nice Body," and take on all sorts of ghosts and ghoullies with your magically charged baton! No translation available.',
    timeToBeat: 2,
  },
];
